// src/main/webapp/app/entities/address/address.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import { Button, InputGroup } from 'reactstrap';
import { AvForm, AvGroup, AvInput } from 'availity-reactstrap-validation';
// TODO import TextFormat only when fieldContainsDate
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, TextFormat } from 'react-jhipster';
import { FaPlus, FaEye, FaPencil, FaTrash, FaSearch } from 'react-icons/lib/fa';

import {
  getSearchEntities,
  getEntities
} from './address.reducer';
 // tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from '../../config/constants';

export interface IAddressProps {
  getEntities: ICrudGetAction;
  getSearchEntities: ICrudGetAction;
  addresses: any[];
  match: any;
}

export interface IAddressState {
  search: string;
}

export class Address extends React.Component<IAddressProps, IAddressState> {
  constructor(props) {
    super(props);
    this.state = {
      search: ''
    };
  }

  componentDidMount() {
    this.props.getEntities();
  }

  search = () => {
    if (this.state.search) {
      this.props.getSearchEntities(this.state.search);
    }
  }

  clear = () => {
    this.props.getEntities();
    this.setState({
      search: ''
    });
  }

  handleSearch = event => this.setState({ search: event.target.value });

  render() {
    const { addresses, match } = this.props;
    return (
      <div>
        <h2>
          <Translate contentKey="worktajmApp.address.home.title">Addresses</Translate>
          <Link to={`${match.url}/new`} className="btn btn-primary float-right jh-create-entity">
            <FaPlus /> <Translate contentKey="worktajmApp.address.home.createLabel" />
          </Link>
        </h2>
        <div className="row">
          <div className="col-sm-12">
            <AvForm onSubmit={this.search}>
              <AvGroup>
                <InputGroup>
                  <AvInput type="text" name="search" value={this.state.search} onChange={this.handleSearch} placeholder={translate('worktajmApp.address.home.search')} />
                  <Button className="input-group-addon">
                    <FaSearch/>
                  </Button>
                  <Button type="reset" className="input-group-addon" onClick={this.clear}>
                    <FaTrash/>
                  </Button>
                </InputGroup>
              </AvGroup>
            </AvForm>
          </div>
        </div>
        <div className="table-responsive">
          <table className="table table-striped">
            <thead>
              <tr>
                <th><Translate contentKey="global.field.id">ID</Translate></th>
                <th ><Translate contentKey="worktajmApp.address.organizationNumber">Organization Number</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.addressLine1">Address Line 1</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.addressLine2">Address Line 2</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.addressLine3">Address Line 3</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.city">City</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.zipOrPostcode">Zip Or Postcode</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.stateProvinceCounty">State Province County</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.country">Country</Translate> <span className="fa fa-sort"/></th>
                <th ><Translate contentKey="worktajmApp.address.addressDetails">Address Details</Translate> <span className="fa fa-sort"/></th>
                <th />
              </tr>
            </thead>
            <tbody>
              {
                addresses.map((address, i) => (
                <tr key={`entity-${i}`}>
                  <td>
                    <Button tag={Link} to={`${match.url}/${address.id}`} color="link" size="sm">
                      {address.id}
                    </Button>
                  </td>
                  <td>
                    {address.organizationNumber}
                  </td>
                  <td>
                    {address.addressLine1}
                  </td>
                  <td>
                    {address.addressLine2}
                  </td>
                  <td>
                    {address.addressLine3}
                  </td>
                  <td>
                    {address.city}
                  </td>
                  <td>
                    {address.zipOrPostcode}
                  </td>
                  <td>
                    {address.stateProvinceCounty}
                  </td>
                  <td>
                    {address.country}
                  </td>
                  <td>
                    {address.addressDetails}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${address.id}`} color="info" size="sm">
                        <FaEye/> <span className="d-none d-md-inline" ><Translate contentKey="entity.action.view" /></span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${address.id}/edit`} color="primary" size="sm">
                        <FaPencil/> <span className="d-none d-md-inline"><Translate contentKey="entity.action.edit" /></span>
                      </Button>
                      <Button tag={Link} to={`${match.url}/${address.id}/delete`} color="danger" size="sm">
                        <FaTrash/> <span className="d-none d-md-inline"><Translate contentKey="entity.action.delete" /></span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))
            }
            </tbody>
          </table>
        </div>
      </div>
    );
  }
}

const mapStateToProps = storeState => ({
  addresses: storeState.address.entities
});

const mapDispatchToProps = { getSearchEntities, getEntities };

export default connect(mapStateToProps, mapDispatchToProps)(Address);

// src/main/webapp/app/entities/address/address.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs/Subscription';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { Address } from './address.model';
import { AddressService } from './address.service';
import { ITEMS_PER_PAGE, Principal, ResponseWrapper } from '../../shared';

@Component({
    selector: 'jhi-address',
    templateUrl: './address.component.html'
})
export class AddressComponent implements OnInit, OnDestroy {

currentAccount: any;
    addresses: Address[];
    error: any;
    success: any;
    eventSubscriber: Subscription;
    currentSearch: string;
    routeData: any;
    links: any;
    totalItems: any;
    queryCount: any;
    itemsPerPage: any;
    page: any;
    predicate: any;
    previousPage: any;
    reverse: any;

    constructor(
        private addressService: AddressService,
        private parseLinks: JhiParseLinks,
        private jhiAlertService: JhiAlertService,
        private principal: Principal,
        private activatedRoute: ActivatedRoute,
        private router: Router,
        private eventManager: JhiEventManager
    ) {
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.routeData = this.activatedRoute.data.subscribe((data) => {
            this.page = data.pagingParams.page;
            this.previousPage = data.pagingParams.page;
            this.reverse = data.pagingParams.ascending;
            this.predicate = data.pagingParams.predicate;
        });
        this.currentSearch = this.activatedRoute.snapshot && this.activatedRoute.snapshot.params['search'] ?
            this.activatedRoute.snapshot.params['search'] : '';
    }

    loadAll() {
        if (this.currentSearch) {
            this.addressService.search({
                page: this.page - 1,
                query: this.currentSearch,
                size: this.itemsPerPage,
                sort: this.sort()}).subscribe(
                    (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
                    (res: ResponseWrapper) => this.onError(res.json)
                );
            return;
        }
        this.addressService.query({
            page: this.page - 1,
            size: this.itemsPerPage,
            sort: this.sort()}).subscribe(
            (res: ResponseWrapper) => this.onSuccess(res.json, res.headers),
            (res: ResponseWrapper) => this.onError(res.json)
        );
    }
    loadPage(page: number) {
        if (page !== this.previousPage) {
            this.previousPage = page;
            this.transition();
        }
    }
    transition() {
        this.router.navigate(['/address'], {queryParams:
            {
                page: this.page,
                size: this.itemsPerPage,
                search: this.currentSearch,
                sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
            }
        });
        this.loadAll();
    }

    clear() {
        this.page = 0;
        this.currentSearch = '';
        this.router.navigate(['/address', {
            page: this.page,
            sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
        }]);
        this.loadAll();
    }
    search(query) {
        if (!query) {
            return this.clear();
        }
        this.page = 0;
        this.currentSearch = query;
        this.router.navigate(['/address', {
            search: this.currentSearch,
            page: this.page,
            sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
        }]);
        this.loadAll();
    }
    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
        this.registerChangeInAddresses();
    }

    ngOnDestroy() {
        this.eventManager.destroy(this.eventSubscriber);
    }

    trackId(index: number, item: Address) {
        return item.id;
    }
    registerChangeInAddresses() {
        this.eventSubscriber = this.eventManager.subscribe('addressListModification', (response) => this.loadAll());
    }

    sort() {
        const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }

    private onSuccess(data, headers) {
        this.links = this.parseLinks.parse(headers.get('link'));
        this.totalItems = headers.get('X-Total-Count');
        this.queryCount = this.totalItems;
        // this.page = pagingParams.page;
        this.addresses = data;
    }
    private onError(error) {
        this.jhiAlertService.error(error.message, null, null);
    }
}

<div>
    <h2>
        <span jhiTranslate="worktajmApp.address.home.title">Addresses</span>
        <button class="btn btn-primary float-right jh-create-entity create-address" [routerLink]="['/', { outlets: { popup: ['address-new'] } }]">
            <span class="fa fa-plus"></span>
            <span class="hidden-sm-down"  jhiTranslate="worktajmApp.address.home.createLabel">
            Create new Address
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-sm-12">
            <form name="searchForm" class="form-inline">
                <div class="input-group w-100 mt-3">
                    <input type="text" class="form-control" [(ngModel)]="currentSearch" id="currentSearch" name="currentSearch" placeholder="{{ 'worktajmApp.address.home.search' | translate }}">
                    <button class="input-group-append btn btn-info" (click)="search(currentSearch)">
                        <span class="fa fa-search"></span>
                    </button>
                    <button class="input-group-append btn btn-danger" (click)="clear()" *ngIf="currentSearch">
                        <span class="fa fa-trash-o"></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="table-responsive" *ngIf="addresses">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="transition.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="organizationNumber"><span jhiTranslate="worktajmApp.address.organizationNumber">Organization Number</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="addressLine1"><span jhiTranslate="worktajmApp.address.addressLine1">Address Line 1</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="addressLine2"><span jhiTranslate="worktajmApp.address.addressLine2">Address Line 2</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="addressLine3"><span jhiTranslate="worktajmApp.address.addressLine3">Address Line 3</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="city"><span jhiTranslate="worktajmApp.address.city">City</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="zipOrPostcode"><span jhiTranslate="worktajmApp.address.zipOrPostcode">Zip Or Postcode</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="stateProvinceCounty"><span jhiTranslate="worktajmApp.address.stateProvinceCounty">State Province County</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="country"><span jhiTranslate="worktajmApp.address.country">Country</span> <span class="fa fa-sort"></span></th>
            <th jhiSortBy="addressDetails"><span jhiTranslate="worktajmApp.address.addressDetails">Address Details</span> <span class="fa fa-sort"></span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let address of addresses ;trackBy: trackId">
                <td><a [routerLink]="['../address', address.id ]">{{address.id}}</a></td>
                <td>{{address.organizationNumber}}</td>
                <td>{{address.addressLine1}}</td>
                <td>{{address.addressLine2}}</td>
                <td>{{address.addressLine3}}</td>
                <td>{{address.city}}</td>
                <td>{{address.zipOrPostcode}}</td>
                <td>{{address.stateProvinceCounty}}</td>
                <td>{{address.country}}</td>
                <td>{{address.addressDetails}}</td>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                [routerLink]="['../address', address.id ]"
                                class="btn btn-info btn-sm">
                            <span class="fa fa-eye"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'address/'+ address.id + '/edit'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-primary btn-sm">
                            <span class="fa fa-pencil"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', { outlets: { popup: 'address/'+ address.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <span class="fa fa-remove"></span>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div *ngIf="addresses && addresses.length">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="queryCount" [maxSize]="5" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>
        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
    </div>
</div>
